print("Hello world")
print("my first code in python")
print("Data Science for life")
print("python coding for life")
print("git is interesting")
print("what a learning day!")
print("T's a learning day")